### ISSUE TITLE
Task failing with error : Enable Java Script on Microsoft Windows Hosted Agents

### ISSUE THREAD

**Issue by mahant-desai** [SwintDC/AzureDevOpsNotifyBuildStatusToBitbucket#1]
I am trying to run the builds using Microsoft Hosted agents. In the pipeline I am using the task "Notify build status to Bitbucket" to update the build status to bit bucket. When I run pipeline, the task is failing to upload the status to Bitbucket. The error details is as below.

**You should enable JavaScript to work with this page. JavaScript load error. We tried to load scripts but something went wrong. Please make sure that your network settings allow you to download scripts from the following**

[build pipeline error.txt](https://github.com/SwintDC/AzureDevOpsNotifyBuildStatusToBitbucket/files/7977424/build.pipeline.error.txt)

I had raised the ticket with Azure Devops Hosted agent support,  https://github.com/actions/virtual-environments/issues/4970,  but they have directed me to raise issue here.

https://github.com/actions/virtual-environments/issues/4970

Any help would really be appreciated.

**Comment by SwintDC** [comment]
Hey,
I myself use this task in an agentless job. If you choose an agentless job, it says "Run on server", whereas, if you use an agent job, it says "Run on agent". That's 1 way to distinguish between the 2 kinds of jobs.
I don't think the task can run on an agent job, it's been a while since I implemented this. But just to be sure, try an agentless job first.

**Comment by SwintDC** [comment]
Since I didn't get any feedback anymore, I will close this issue
